services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vpti_backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    networks:
      - vpti_internal_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vpti_frontend
    restart: unless-stopped
    env_file:
      - ./frontend/.env.local
    ports:
      - "3005:3000"
    environment:
      VIRTUAL_HOST: taskmanager.adantechti.com
    depends_on:
      - backend
    networks:
      - vpti_internal_net
    

networks:
  vpti_internal_net:
    name: vpti_internal_net
    driver: bridge
